def f():
    raise Exception('This is the error message.')

a = f()
